version: '3'
services:
  palworld-server:
    image: czy0612/palworld-server:latest
    ports:
      - "8211:8211/udp"
      - "25575:25575"
    volumes:
      - "./data:/home/steam/Steam/steamapps/common/PalServer"
